.core-defs:
  variables:
    CORENAME: mupen64plus_next

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

libretro-build-linux-x64:
  variables:
    HAVE_PARALLEL_RDP: 1
    HAVE_PARALLEL_RSP: 1
    HAVE_THR_AL: 1
    LLE: 1
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default

libretro-build-windows-x64-mingw:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default

libretro-build-libnx-aarch64:
  extends:
    - .core-defs
    - .libretro-libnx-static-retroarch-master
